# Copyright (C) 2022  Fabrice Nicol
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM ubuntu:21.10

# for apt to be noninteractive

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
RUN apt update && apt upgrade -y

# build essentials

RUN apt install -y wget git xz-utils build-essential flex bison libtool texinfo info \
                   libgif-dev libgnutls28-dev mailutils pkg-config \
                   libncurses-dev libxaw7-dev libjpeg-dev libpng-dev libtiff-dev
# download auxiliary ROTD build, to bootstrap image building

RUN wget https://github.com/fabnicol/ubuntu4mercury/releases/download/v1.0.1/rotd.tar.xz
RUN tar xJvf rotd.tar.xz && rm rotd.tar.xz
RUN echo PATH='/usr/local/mercury-rotd-@/bin:$PATH' >> /etc/profile
RUN wget https://github.com/Mercury-Language/mercury-srcdist/archive/refs/tags/rotd-@.tar.gz
RUN tar xzvf rotd-@.tar.gz
RUN echo 'source /etc/profile' >> /root/.bashrc

# rebuild the same ROTD dated -@ within the docker image for security-minded users
# using ENV as sourcing /etc/profile will do only when the image is created, not while building it.

ENV PATH=/usr/local/mercury-rotd-2022-01-09/bin:$PATH
RUN cd mercury-srcdist-rotd-@ && /bin/bash configure && make install PARALLEL=-j4
RUN rm -rf /mercury-srcdist-rotd-@
RUN if [ "-@" != "-2022-01-09" ]; then rm -rf /usr/local/mercury-rotd-2022-01-09; fi
# now with this secured ROTD build the Mercury git source
RUN git clone --shallow-since=2022-01-08 \
              -b master https://github.com/Mercury-Language/mercury.git \
              && cd /mercury && git reset --hard REVISION
              
# Now use the fresh ROTD dated -@ to build the git source at revision REVISION
# synchronize the ROTD and git source dates otherwise it may not build              

ENV PATH=/usr/local/mercury-rotd-@/bin:$PATH              
RUN cd /mercury \
   && /bin/bash prepare.sh && /bin/bash configure --disable-most-grades \
   && make install PARALLEL=-j4
RUN echo PATH='$PATH:/usr/local/mercury-DEV/bin' >> /etc/profile
RUN rm -rf /mercury

# do the same for emacs, with Mercury support for etags (source code tagging)

RUN echo cloning since date="EMACS_DATE" rev="EMACS_REV" \
    && git clone --shallow-since="EMACS_DATE" -b master --single-branch git://git.sv.gnu.org/emacs.git \
    && cd emacs && git reset --hard "EMACS_REV"
    
RUN cd emacs && /bin/bash autogen.sh \
   && /bin/bash configure --prefix=/usr/local/emacs-DEV \
   && make install -j4
   
# companion tools, you may add tools to his list below as you wish:

RUN apt install -y vim nano gdb

# adjust paths and cleanup

RUN echo PATH='$PATH:/usr/local/emacs-DEV/bin' >> /etc/profile
RUN echo MANPATH='$MANPATH:/usr/local/mercury-rotd-@/man' >> /etc/profile
RUN echo INFOPATH='$INFOPATH:/usr/local/mercury-rotd-@/info' >> /etc/profile
RUN echo "(add-to-list 'load-path \n\
\"/usr/local/mercury-rotd-@/lib/mercury/elisp\") \n\
(autoload 'mdb \"gud\" \"Invoke the Mercury debugger\" t)" >> /root/.emacs
RUN rm -rf /emacs
RUN echo '#!/bin/bash \n\
PATH0=$PATH \n\
PATH=/usr/local/mercury-DEV/bin:$PATH mmc "$@" \n\
PATH=$PATH0' > /usr/local/bin/mmc-dev && chmod +x /usr/local/bin/mmc-dev
RUN echo '#!/bin/bash \n\
PATH0=$PATH \n\
PATH=/usr/local/mercury-DEV/bin:$PATH mmake "$@" \n\
PATH=$PATH0' > /usr/local/bin/mmake-dev && chmod +x /usr/local/bin/mmake-dev
RUN apt -y autoremove --purge && apt -y clean
