# Copyright (C) 2022  Fabrice Nicol
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM ubuntu:21.10

# For apt to be noninteractive.

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
RUN apt update && apt upgrade -y

# Build essentials

RUN apt -y install gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" \
    |  tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt update
RUN apt install -y wget git xz-utils build-essential flex bison libtool texinfo info \
                   libgif-dev libgnutls28-dev mailutils pkg-config \
                   libncurses-dev libxaw7-dev libjpeg-dev libpng-dev libtiff-dev \
                   default-jre default-jdk
RUN apt -y install mono-devel


# Download from Github first then if not available from official website.

RUN wget https://dl.mercurylang.org/rotd/mercury-srcdist-rotd-@.tar.gz -O rotd-@.tar.gz
RUN tar xzvf rotd-@.tar.gz && rm -vf rotd-@.tar.gz
RUN echo 'source /etc/profile' >> /root/.bashrc

# Rebuild the same ROTD dated -@ within the docker image for security-minded users.
# Using ENV as sourcing /etc/profile will do only when the image is created, not while building it.

ENV THREADS=THREADS_FOUND
ENV [ ${THREADS} = 0 ] && THREADS=1
RUN echo "Using ${THREADS} for building."
RUN cd mercury-srcdist-rotd-@ && /bin/bash configure && make install PARALLEL=-j${THREADS}
RUN rm -rf /mercury-srcdist-rotd-@

# Now with this secured ROTD build the Mercury git source.

RUN git clone --shallow-since=GIT_SOURCE_SINCE \
              -b master https://github.com/Mercury-Language/mercury.git \
              && cd /mercury && git reset --hard REVISION

# Now use the fresh ROTD dated -@ to build the git source at revision REVISION.
# Synchronize the ROTD and git source dates otherwise it may not build.

ENV PATH=/usr/local/mercury-rotd-@/bin:$PATH
RUN cd /mercury \
   && /bin/bash prepare.sh && /bin/bash configure --disable-most-grades \
   && make install PARALLEL=-j${THREADS} && git rev-parse HEAD > ../GIT_HEAD
RUN echo PATH='$PATH:/usr/local/mercury-rotd-@/bin:/usr/local/mercury-DEV/bin' >> /etc/profile
RUN rm -rf /mercury

# Do the same for emacs, with Mercury support for etags (source code tagging).

RUN echo cloning since date="EMACS_DATE" rev="EMACS_REV" \
    && git clone --shallow-since="EMACS_DATE" -b master git://git.sv.gnu.org/emacs.git \
    && cd emacs && git reset --hard "EMACS_REV"

RUN cd emacs && /bin/bash autogen.sh \
   && /bin/bash configure --without-tiff \
                          --without-jpeg \
			  --without-png \
			  --without-gif \
                          --prefix=/usr/local/emacs-DEV \
   && make install -j${THREADS}

# Companion tools, you may add tools to his list below as you wish:

RUN apt install -y vim nano gdb

# Adjust paths and cleanup.

RUN echo PATH='$PATH:/usr/local/emacs-DEV/bin' >> /etc/profile
RUN echo MANPATH='$MANPATH:/usr/local/mercury-rotd-@/man' >> /etc/profile
RUN echo INFOPATH='$INFOPATH:/usr/local/mercury-rotd-@/info' >> /etc/profile
RUN echo "(add-to-list 'load-path \n\
\"/usr/local/mercury-rotd-@/lib/mercury/elisp\") \n\
(autoload 'mdb \"gud\" \"Invoke the Mercury debugger\" t)" >> /root/.emacs
RUN rm -rf /emacs
RUN echo '#!/bin/bash \n\
PATH0=$PATH \n\
PATH=/usr/local/mercury-DEV/bin:$PATH mmc "$@" \n\
PATH=$PATH0' > /usr/local/bin/mmc-dev && chmod +x /usr/local/bin/mmc-dev
RUN echo '#!/bin/bash \n\
PATH0=$PATH \n\
PATH=/usr/local/mercury-DEV/bin:$PATH mmake "$@" \n\
PATH=$PATH0' > /usr/local/bin/mmake-dev && chmod +x /usr/local/bin/mmake-dev
RUN apt -y autoremove --purge && apt -y clean
